# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Aliases
alias ls='eza'
alias ll='eza -lah'
alias cat='bat'
alias grep='grep --color=auto'

eval "$(zoxide init --cmd cd bash)"

# Bash prompt
PS1="\[\e[32m\][\u@\h \W]$\[\e[0m\] "
